[package]
name = "manga_reader"
version = "0.1.0"
authors = ["Xavier Schiller <22575255+XavierSchiller@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
zip = "0.5.8"